[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30" # Usa la versión exacta de tu pragma

# Configuración de Endpoints RPC
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" # Para el fork de testing
sepolia = "${SEPOLIA_RPC_URL}" # Para el despliegue

# Configuración de testing avanzada (puedes dejarlas por defecto si no usas Fuzz/Invariant)
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15
